<?php

/**
 * @file
 * Contains unb_libraries_askus.module.
 */

use Drupal\Component\Utility\UrlHelper;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function unb_libraries_askus_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the unb_libraries_askus module.
    case 'help.page.unb_libraries_askus':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('UNB Libraries chat feature powered by LibraryH3lp.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements Ask Us chat widget.
 */
function _unb_libraries_askus_chat_widget($widget_style = "pop-up", $queue = "askus", $title = "Ask Us") {
  $xml_show = _unb_libraries_askus_check_presence($queue);
  // Process title to be used as argument.
  $title = trim($title);
  $title = preg_replace('/\s+/', '+', $title);
  // For alternative themes see: https://libraryh3lp.com/presence/themes.
  $theme = 'gota';
  // Construct chat widget address.
  $ask_src = '//ca.libraryh3lp.com/chat/' . $queue .
    '@chat.ca.libraryh3lp.com?title=' . $title .
    '&amp;theme=' . $theme .
    '&amp;css=//' . $_SERVER['SERVER_NAME'] . '/core/css-2015/libraryh3lp.unb.lib.css';

  return _unb_libraries_askus_render_widget($xml_show, $ask_src, $title, $widget_style);
}

/**
 * Implements Server-Side Presence Check.
 *
 * @param string $queue
 *   The user/queue name to check presence for, our default queue = askus.
 *
 * @return string
 *   The XMPP (Jabber) protocol response from the presence check.
 *
 * @see http://docs.libraryh3lp.com/code-presence-check-php.html
 */
function _unb_libraries_askus_check_presence($queue = 'askus') {
  // Resource URL : {host}/presence/jid/{name}/[chat.]libraryh3lp.com/{format}[/{theme}].
  // {host} : served over both HTTP and HTTPS (we use HTTPS).
  // {name} : we only use 'queue' type therefore must include the optional '[chat.]'.
  // {format} : specifies format for the presence indicator - can be text, xml, js, or image (we use xml).
  // [/{theme}] : specifies optional theme when choosing image for {format} (we dont use).
  $host = 'https://ca.libraryh3lp.com';
  $name = trim($queue) . '/chat.';
  $format = 'xml';
  $url = UrlHelper::filterBadProtocol(
    $host .
    '/presence/jid/' .
    $name .
    'ca.libraryh3lp.com/' .
    $format
  );
  $doc = new DOMDocument();
  $doc->load($url);

  $jabber_resources = $doc->getElementsByTagName('resource');
  if ($jabber_resources->length > 0) {
    $xml_show = $jabber_resources
      ->item(0)
      ->getAttribute('show');
  }
  else {
    $xml_show = 'Error: no presence resource';
  }

  return $xml_show;
}

/**
 * If queue online, output appropriate style widget else output offline message.
 *
 * @param string $xml_show
 *   The user/queue name to check presence status for, UNB Libraries default queue = askus.
 * @param string $ask_src
 *   The user/queue name to check presence status for, UNB Libraries default queue = askus.
 * @param string $title
 *   The title text for the heading tag.
 * @param string $widget_style
 *   The user/queue name to check presence status for, UNB Libraries default queue = askus.
 *
 * @return string
 *   The html of the chat widget.
 */
function _unb_libraries_askus_render_widget($xml_show, $ask_src, $title, $widget_style) {
  $html = '<div class="askus">';
  $html .= '<h2>' . $title . '</h2>';
  $html .= '<noscript><p>Ask Us instant messaging requires JavaScript.</p></noscript>';

  if ($xml_show != 'available') {
    if (in_array($xml_show, ['dnd', 'away'])) {
      $note = 'AskUs is currently busy serving other patrons.';
    }
    else {
      $note = 'Ask Us is currently <strong>offline</strong>strong>. Get custom note from _getOfflineNote()';
    }
    $html .= '<p class="askus-offline">';
    $html .= $note . '<br />';
    $html .= '</p>';
  }
  elseif ($widget_style == 'embedded') {
    // Render embedded chat widget.
    $html .= '<div class="chatWidget needs-js" style="position:relative;z-index:0;">';
    $html .= '<iframe src="' . $ask_src . '" frameborder="0"></iframe>';
    $html .= '</div>';
  }
  else {
    // Render pop-up chat widget.
    $sendTxt = 'Type here to CHAT.';
    $html .= '<div class="askus-chatbox">';
    $html .= '<a class="askus-popup" href="' . $ask_src . '">' . $sendTxt . '</a>';
    $html .= '</div>';
  }

  $html .= '<p>';
  $html .= '<a href="/help/ask"><span class="sr-only">Ask by:</span>';
  $html .= '<span><i class="fas fa-envelope"></i> Email</span>';
  $html .= '<span><i class="fas fa-sms"></i> Text</span>';
  $html .= '<span><i class="fas fa-phone"></i> Phone</span>';
  $html .= '<span><i class="fas fa-walking"></i> In-Person</span>';
  $html .= '</a>';
  $html .= '</p>';
  $html .= '</div>';

  return $html;
}
