<?php

/**
 * @file
 * Contains unb_libraries_askus.module.
 */

use Drupal\Component\Utility\UrlHelper;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function unb_libraries_askus_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the unb_libraries_askus module.
    case 'help.page.unb_libraries_askus':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('UNB Libraries chat feature powered by LibraryH3lp.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements Ask Us chat widget.
 */
function _unb_libraries_askus_chat_widget($title, $widget_style, $queue = "askus") {
  $xml_show = _unb_libraries_askus_check_presence($queue);

  // Process title to be used as argument.
  $title = trim($title);

  // Construct chat widget address.
  // For alternative themes see: https://libraryh3lp.com/presence/themes.
  $ask_src_title = 'Ask+Us';
  $theme = 'gota';
  $css_file = 'https://lib.unb.ca/core/css-2015/libraryh3lp.unb.lib.css';
  $ask_src = 'https://ca.libraryh3lp.com/chat/' . $queue .
    '@chat.ca.libraryh3lp.com?title=' . $ask_src_title .
    '&amp;theme=' . $theme .
    '&amp;css=' . $css_file;

  return _unb_libraries_askus_get_html($title, $widget_style, $ask_src, $xml_show);
}

/**
 * Implements Server-Side Presence Check.
 *
 * @param string $queue
 *   The user/queue name to check presence for, our default queue = askus.
 *
 * @return string
 *   The XMPP (Jabber) protocol response from the presence check.
 *
 * @see http://docs.libraryh3lp.com/code-presence-check-php.html
 */
function _unb_libraries_askus_check_presence($queue = 'askus') {
  // Resource URL : {host}/presence/jid/{name}/[chat.]libraryh3lp.com/{format}[/{theme}].
  // {host} : served over both HTTP and HTTPS (we use HTTPS).
  // {name} : we only use 'queue' type therefore must include the optional '[chat.]'.
  // {format} : specifies format fo presence indicator - can be text, xml, js, or image (we use xml).
  // [/{theme}] : specifies optional theme when choosing image for {format} (we dont use).
  $host = 'https://ca.libraryh3lp.com';
  $name = trim($queue) . '/chat.';
  $format = 'xml';
  $url = UrlHelper::filterBadProtocol(
    $host .
    '/presence/jid/' .
    $name .
    'ca.libraryh3lp.com/' .
    $format
  );
  $doc = new DOMDocument();
  $doc->load($url);

  $jabber_resources = $doc->getElementsByTagName('resource');
  if ($jabber_resources->length > 0) {
    $xml_show = $jabber_resources
      ->item(0)
      ->getAttribute('show');
  }
  else {
    $xml_show = 'Error: no presence response!';
  }

  return $xml_show;
}

/**
 * If queue online, output appropriate style widget else output offline message.
 *
 * @param string $title
 *   The title text for the heading tag.
 * @param string $widget_style
 *   The user/queue name to check presence status for, UNB Libraries default queue = askus.
 * @param string $ask_src
 *   The user/queue name to check presence status for, UNB Libraries default queue = askus.
 * @param string $xml_show
 *   The user/queue name to check presence status for, UNB Libraries default queue = askus.
 *
 * @return string
 *   The html of the chat widget.
 */
function _unb_libraries_askus_get_html($title, $widget_style, $ask_src, $xml_show) {
  if ($widget_style == 'embedded') {
    // Provide embedded chat widget.
    $wrapperclass = 'chat-embedded';
    $chatbox = '<iframe src="' . $ask_src . '"></iframe>';
  }
  else {
    // Provide default pop-up chat widget.
    $wrapperclass = 'chat-popup';
    $chatbox = '<p class="askus-note-online">';
    $chatbox .= '<a href="' . $ask_src . '">Type here to CHAT.</a>';
    $chatbox .= '</p>';

    // Hide popup chat heading text because of background image.
    $title = '<span class="sr-only">' . $title . '</span>';
  }

  if ($xml_show != 'available') {
    if (in_array($xml_show, ['dnd', 'away'])) {
      $chatbox = '<p class="askus-note-busy">';
      $chatbox .= 'Ask Us is currently busy serving other patrons.';
      $chatbox .= '</p>';
    }
    else {
      $chatbox = '<p class="askus-note-offline">';
      $chatbox .= 'Ask Us is currently <strong>offline</strong>. ';
      $chatbox .= _unb_libraries_askus_get_offline_note();
      $chatbox .= '</p>';
    }
  }

  $wrapperstart = '<div class="' . $wrapperclass . '">';
  $header = '<h2>' . $title . '</h2>';
  $body = '<noscript><p>Ask Us chat requires JavaScript.</p></noscript>';
  $body .= '<div class="libraryh3lp requires-js">';
  $body .= $chatbox;
  $body .= '</div>';
  if ($widget_style != 'embedded') {
    $footer = '<p class="askus-footer">';
    $footer .= '<a href="/help/ask"><span class="sr-only">Ask by:</span>';
    $footer .= '<span><i class="fas fa-envelope"></i> Email</span>';
    $footer .= '<span><i class="fas fa-sms"></i> Text</span>';
    $footer .= '<span><i class="fas fa-phone"></i> Phone</span>';
    $footer .= '<span><i class="fas fa-walking"></i> In-Person</span>';
    $footer .= '</a>';
    $footer .= '</p>';
  }
  else {
    $footer = NULL;
  }
  $wrapperend = '</div>';

  return $wrapperstart . $header . $body . $footer . $wrapperend;
}

/**
 * If queue is offline, output message including the time and day it chat 're-opens'.
 *
 * @return string
 *   The offline re-open text.
 */
function _unb_libraries_askus_get_offline_note() {
  // Note: Integrate with Hours module when ready.
  $note = 'Chat service will re-open at [time] [day].';

  return $note;
}
