<?php

/**
 * @file
 * Contains eresources.module.
 */

/**
 * Implements hook_theme().
 */
function eresources_theme($existing, $type, $theme, $path) {
  return [
    'license' => [
      'variables' => [
        'license' => NULL,
      ],
    ],
    'license-multi' => [
    ],
    'eresources-local' => [
      'variables' => [
        'eresources' => NULL,
        'form_id' => NULL,
        'debug' => NULL,
      ],
    ],
    'eresources-kb' => [
      'variables' => [
        'eresources' => NULL,
        'form_id' => NULL,
        'debug' => NULL,
      ],
    ],
    'trials' => [
      'variables' => [
        'eresources' => NULL,
      ],
    ],
    'permalink' => [
      'variables' => [
        'entry' => NULL,
        'debug' => NULL,
      ],
    ],
    'eresources_record' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for eresources_record templates.
 *
 * Default template: eresources-record.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the user information and any
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_eresources_record(array &$variables) {
  $variables['eresources_record'] = $variables['elements']['#eresources_record'];
}
