<?php

/**
 * @file
 * Contains eresources.module.
 */

/**
 * Implements hook_theme().
 */
function eresources_theme($existing, $type, $theme, $path) {
  return [
    'license' => [
      'variables' => [
        'license' => NULL,
      ],
    ],
    'eresources-local' => [
      'variables' => [
        'eresources' => NULL,
        'form_id' => NULL,
      ],
    ],
    'eresources-kb' => [
      'variables' => [
        'eresources' => NULL,
        'form_id' => NULL,
      ],
    ],
    'trials' => [
      'variables' => [
        'eresources' => NULL,
      ],
    ],
    'permalink' => [
      'variables' => [
        'entry' => NULL,
      ],
    ],
  ];
}
