<?php

/**
 * @file
 * Contains lib_core.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_theme().
 */
function lib_core_theme($existing, $type, $theme, $path) {
  return [
    'help_info' => [
      'variables' => ['info' => NULL],
    ],
  ];
}

/**
 * Implements hook_editor_js_settings_alter().
 *
 * @see https://www.drupal.org/project/colorbutton/issues/2910028
 */
function lib_core_editor_js_settings_alter(array &$settings) {
  $extra_editor_settings = [
    'colorButton_foreStyle' => [
      'element' => 'span',
      'attributes' => [
        'data-color' => '#(color)',
      ],
    ],
  ];

  if (array_key_exists('library_page_html', $settings['editor']['formats'])) {
    $settings['editor']['formats']['library_page_html']['editorSettings'] += $extra_editor_settings;
  }
}

/**
 * Implements hook_entity_presave().
 */
function lib_core_entity_presave(EntityInterface $entity) {
  switch ($entity->bundle()) {
    case 'faculties':
      $name = $entity->getName();
      $selected_campus = $entity
        ->get('field_campus')
        ->getString();

      $campus_options = array_keys(
        $entity
          ->get('field_campus')
          ->getSetting('allowed_values')
      );
      // Strip any allowed, appended campus key from name field for display name.
      $display_name = trim(str_replace($campus_options, "", $name));
      $entity->set('field_display_name', $display_name);
      // Append current selected campus key to term name.
      $entity->setName($display_name . ' ' . $selected_campus);
      break;
  }
}

/**
 * Implements hook_form_alter().
 */
function lib_core_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    case 'entity_browser_media_entity_browser_form':
      // Add entity browser library for improvements.
      $form['#attached']['library'][] = 'lib_core/table-row-check';
      break;

    case 'node_library_page_form':
    case 'node_library_page_edit_form':
      // Attach CSS libraries for Library page content type form enhancements.
      $form['#attached']['library'][] = 'lib_unb_ca/global-styling';
      $form['#attached']['library'][] = 'lib_core/ckeditor_stylesheets';
      $form['#attached']['library'][] = 'lib_core/admin-overrides';
      break;

    case 'node_news_post_form':
    case 'node_news_post_edit_form':
      $form['#attached']['library'][] = 'lib_core/bootstrap-cdn';
      $form['#attached']['library'][] = 'lib_core/admin-overrides';
      $form['#attached']['library'][] = 'lib_core/ckeditor_stylesheets';
      $form['promote']['widget']['value']['#title'] = t('Set as rotating front page feature');
      break;

    case 'webform_submission_purchase_suggestion_add_form':
      $form['#attached']['library'][] = 'lib_core/lib-chosen';
      $form['#attached']['library'][] = 'lib_core/chosen-bootstrap';
      break;

    case 'webform_submission_contact_add_form':
      $recipient = explode("@unb.ca", $form['elements']['recipient']['#default_value']);
      $username = $recipient[0];

      if ($user = user_load_by_name($username)) {
        $alert_msg =
          '<div class="d-flex">' .
            '<div class="pr-1"><i class="fas fa-info-circle"></i></div>' .
            '<div class="align-self-start">Please complete the following webform to send email to <b>' .
              $user->get('field_first_name')->getString() . ' ' .
              $user->get('field_last_name')->getString() . '</b>. ' .
              'You may also <a href="mailto:' . $username .
              '@unb.ca?subject=Patron Webform Query">use your own email program</a>, if configured.
            </div>' .
          '</div>';
      }
      elseif ($department = _lib_core_contactable_department($username)) {
        $alert_msg =
          '<div class="d-flex">
            <div class="pr-1"><i class="fas fa-info-circle"></i></div>
            <div class="align-self-start">';

        // Custom alert for 'Web Feedback' form, aka Website Administrator (libweb).
        $alert_msg .=
          ($username == 'libweb')
          ? 'Please let us know if you experience any difficulties in accessing our pages or find content which you
             believe is inaccurate. General suggestions, questions, or comments about this website can be directed to
             our <a href="/services/your-comments-and-suggestions">Suggestion Form</a>.'
          : 'Please complete the following webform to send email to <b>' .
            $department . '</b>. You may also <a href="mailto:' . $username .
            '@unb.ca?subject=Patron Webform Query">use your own email program</a>, if configured.';
        $alert_msg .=
            '</div>
          </div>';
      }
      else {
        $alert_msg = FALSE;
      }

      if ($alert_msg) {
        $form['elements']['contact_message']['#message_message']['#markup'] = $alert_msg;

        // Change 'Email Us' fieldset label for 'Web Feedback' form.
        if ($username == 'libweb') {
          $form['elements']['email_us']['#title'] = 'Email our Website Administrator';
        }
      }
      else {
        // Somebody messed with form argument (or perhaps email id typo) - prevent submissions.
        $form['actions']['submit']['#attributes']['disabled'] = 'disabled';
        $form['elements']['contact_message']['#message_message']['#markup'] =
          '<div class="d-flex">
            <div class="pr-1"><i class="fas fa-exclamation-triangle"></i></div>
            <div class="align-self-start">Sorry, <b>' .
              $username . '</b> is not a valid UNB Libraries recipient. Messaging is <b>disabled</b>.
            </div>
           </div>';
      }
      break;

    default:
      break;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function lib_core_preprocess_node__news_post(&$variables) {
  $node = $variables['node'];

  $node_authoredon = $node->getCreatedTime();
  $formatted_date = \Drupal::service('date.formatter')->format($node_authoredon, 'metadata_date');
  $variables['formatted_date'] = $formatted_date;

  $fname = $node
    ->getOwner()
    ->get('field_first_name')
    ->getString();
  $lname = $node
    ->getOwner()
    ->get('field_last_name')
    ->getString();
  $author = $fname . ' ' . $lname;
  $variables['author'] = $lname ? $author : 'Admin';

  $stickied = $node->isSticky();
  $variables['stickied'] = $stickied;
}

/**
 * Port get_guide_categories() from core/inc-2015/guide_categories.php.
 *
 * @return array
 *   The array of Research Subjects.
 */
function _lib_core_get_guide_categories() {
  $categories = [
    'anthropology' => 'Anthropology',
    'biology' => 'Biology',
    'business' => 'Business & Management',
    'chemistry' => 'Chemistry',
    'classics' => 'Classics and Ancient History',
    'computerscience' => 'Computer Science',
    'criminology' => 'Criminology',
    'development' => 'International Development Studies',
    'earth-sciences' => 'Earth Sciences',
    'economics' => 'Economics',
    'education' => 'Education',
    'engineering' => 'Engineering',
    'english' => 'English',
    'entrepreneurship' => 'Entrepreneurship',
    'familyviolence' => 'Family Violence Issues',
    'film' => 'Film Studies',
    'finearts' => 'Fine Arts',
    'forestry' => 'Forestry & Environmental Management',
    'french' => 'French',
    'german' => 'German Literature',
    'gerontology' => 'Gerontology',
    'history' => 'History',
    'ics' => 'Communication Studies',
    'journalism' => 'Journalism & Communications',
    'kinesiology' => 'Kinesiology',
    'law' => 'Law',
    'math' => 'Mathematics',
    'media' => 'Media Arts and Culture',
    // 'miscellaneous' => 'Miscellaneous',
    'music' => 'Music',
    'nativestudies' => 'Native Studies',
    'nursing' => 'Nursing & Health Sciences',
    'philosophy' => 'Philosophy',
    'physics' => 'Physics',
    'politicalscience' => 'Political Science',
    'psychology' => 'Psychology',
    'religiousstudies' => 'Religious Studies',
    'sts' => 'Science & Technology Studies',
    'socialwork' => 'Social Work',
    'sociology' => 'Sociology',
    'spanish' => 'Spanish Literature',
    'womensstudies' => 'Gender and Women\'s Studies',
  ];
  asort($categories);

  return $categories;
}

/**
 * Get UNB Libraries department label, given an email mailbox.
 *
 * @param string $mailbox
 *   A email mailbox string identifying a UNB Libraries Department without a Drupal user account.
 *
 * @return string
 *   The name of the UNB Libraries department.
 */
function _lib_core_contactable_department($mailbox) {
  // Contact webform may send messages to the following mailboxes.
  $departments = [
    'archives' => 'Archives',
    'circhi' => 'Access Services',
    'digitalscholar' => 'Centre for Digital Scholarship',
    'docdel' => 'Document Delivery',
    'englib' => 'Engineering & Computer Science',
    'hilref' => 'Reference',
    'library' => 'Administration',
    'libweb' => 'Website Administrator',
    'govdocs' => 'Government Documents, Data and Maps',
    'hwkcommons' => 'Hans W. Klohn Commons',
    'lawlib' => 'Law Library',
    'mic' => 'Microforms',
    'scilib' => 'Science & Forestry',
  ];

  return array_key_exists($mailbox, $departments) ? $departments[$mailbox] : NULL;
}

/**
 * Implements hook_views_query_alter().
 */
function lib_core_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  if ($view->id() != 'content') {
    return;
  }

  $user = Drupal::currentUser();
  if (!$user->hasPermission('edit any library_page content')) {
    $query->addWhere(1, 'type', 'library_page', '!=');
  }
  if (!$user->hasPermission('edit any news_post content')) {
    $query->addWhere(1, 'type', 'news_post', '!=');
  }
}
