<?php

/**
 * @file
 * Contains lib_core.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_editor_js_settings_alter().
 *
 * @see https://www.drupal.org/project/colorbutton/issues/2910028
 */
function lib_core_editor_js_settings_alter(array &$settings) {
  $extra_editor_settings = [
    'colorButton_foreStyle' => [
      'element' => 'span',
      'attributes' => [
        'data-color' => '#(color)',
      ],
    ],
  ];

  if (array_key_exists('library_page_html', $settings['editor']['formats'])) {
    $settings['editor']['formats']['library_page_html']['editorSettings'] += $extra_editor_settings;
  }
}

/**
 * Implements hook_form_alter().
 */
function lib_core_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    case 'entity_browser_media_entity_browser_form':
      // Add entity browser library for improvements.
      $form['#attached']['library'][] = 'lib_core/table-row-check';
      break;

    case 'node_library_page_form':
    case 'node_library_page_edit_form':
      // Attach CSS libraries for Library page content type form enhancements.
      $form['#attached']['library'][] = 'lib_unb_ca/global-styling';
      $form['#attached']['library'][] = 'lib_core/ckeditor_stylesheets';
      $form['#attached']['library'][] = 'lib_core/admin-overrides';
      break;

    case 'node_news_post_form':
    case 'node_news_post_edit_form':
      $form['#attached']['library'][] = 'lib_core/bootstrap-cdn';
      $form['#attached']['library'][] = 'lib_core/admin-overrides';
      $form['#attached']['library'][] = 'lib_core/ckeditor_stylesheets';
      $form['promote']['widget']['value']['#title'] = t('Set as rotating front page feature');
      break;

    case 'webform_submission_purchase_suggestion_add_form':
      $form['#attached']['library'][] = 'lib_core/lib-chosen';
      $form['#attached']['library'][] = 'lib_core/chosen-bootstrap';
      break;

    case 'webform_submission_contact_add_form':
      $recipient = explode("@unb.ca", $form['elements']['recipient']['#default_value']);
      $username = $recipient[0];

      if ($user = user_load_by_name($username)) {
        $success_msg =
          '<div class="d-flex">' .
            '<div class="pr-1"><i class="fas fa-info-circle"></i></div>' .
            '<div class="align-self-start">Please complete the following webform to send email to <b>' .
              $user->get('field_first_name')->getString() . ' ' .
              $user->get('field_last_name')->getString() . '</b>. ' .
              'You may also <a href="mailto:' . $username .
              '@unb.ca?subject=Patron Webform Query">use your own email program</a>, if configured.
            </div>' .
          '</div>';
      }
      elseif ($department = _lib_core_contactable_department($username)) {
        $success_msg =
          '<div class="d-flex">' .
            '<div class="pr-1"><i class="fas fa-info-circle"></i></div>' .
            '<div class="align-self-start">Please complete the following webform to send email to <b>' .
              $department . '</b>. You may also <a href="mailto:' . $username .
              '@unb.ca?subject=Patron Webform Query">use your own email program</a>, if configured.
            </div>
          </div>';
      }
      else {
        $success_msg = FALSE;
      }

      if ($success_msg) {
        $form['elements']['contact_message']['#message_message']['#markup'] = $success_msg;
      }
      else {
        $form['actions']['submit']['#attributes']['disabled'] = 'disabled';
        $form['elements']['contact_message']['#message_message']['#markup'] =
          '<div class="d-flex">
            <div class="pr-1"><i class="fas fa-exclamation-triangle"></i></div>
            <div class="align-self-start">Sorry, <b>' .
              $username . '</b> is not a valid UNB Libraries recipient. Messaging is <b>disabled</b>.
            </div>
           </div>';
      }
      break;

    default:
      break;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function lib_core_preprocess_node__news_post(&$variables) {
  $node = $variables['node'];

  $node_authoredon = $node->getCreatedTime();
  $formatted_date = \Drupal::service('date.formatter')->format($node_authoredon, 'metadata_date');
  $variables['formatted_date'] = $formatted_date;

  $fname = $node
    ->getOwner()
    ->get('field_first_name')
    ->getString();
  $lname = $node
    ->getOwner()
    ->get('field_last_name')
    ->getString();
  $author = $fname . ' ' . $lname;
  $variables['author'] = $lname ? $author : 'Admin';

  $stickied = $node->isSticky();
  $variables['stickied'] = $stickied;
}

/**
 * Port get_guide_categories() from core/inc-2015/guide_categories.php.
 *
 * @return array
 *   The array of Research Subjects.
 */
function _lib_core_get_guide_categories() {
  $categories = [
    'anthropology' => 'Anthropology',
    'biology' => 'Biology',
    'business' => 'Business & Management',
    'chemistry' => 'Chemistry',
    'classics' => 'Classics and Ancient History',
    'computerscience' => 'Computer Science',
    'criminology' => 'Criminology',
    'development' => 'International Development Studies',
    'earth-sciences' => 'Earth Sciences',
    'economics' => 'Economics',
    'education' => 'Education',
    'engineering' => 'Engineering',
    'english' => 'English',
    'entrepreneurship' => 'Entrepreneurship',
    'familyviolence' => 'Family Violence Issues',
    'film' => 'Film Studies',
    'finearts' => 'Fine Arts',
    'forestry' => 'Forestry & Environmental Management',
    'french' => 'French',
    'german' => 'German Literature',
    'gerontology' => 'Gerontology',
    'history' => 'History',
    'ics' => 'Communication Studies',
    'journalism' => 'Journalism & Communications',
    'kinesiology' => 'Kinesiology',
    'law' => 'Law',
    'math' => 'Mathematics',
    'media' => 'Media Arts and Culture',
    // 'miscellaneous' => 'Miscellaneous',
    'music' => 'Music',
    'nativestudies' => 'Native Studies',
    'nursing' => 'Nursing & Health Sciences',
    'philosophy' => 'Philosophy',
    'physics' => 'Physics',
    'politicalscience' => 'Political Science',
    'psychology' => 'Psychology',
    'religiousstudies' => 'Religious Studies',
    'sts' => 'Science & Technology Studies',
    'socialwork' => 'Social Work',
    'sociology' => 'Sociology',
    'spanish' => 'Spanish Literature',
    'womensstudies' => 'Gender and Women\'s Studies',
  ];
  asort($categories);

  return $categories;
}

/**
 * Get eResources titles. Switch to MySQL Server query by launch.
 *
 * @return array
 *   The array of eResource Titles.
 */
function _lib_core_get_database_titles() {
  $titles = [
    '3606' => '17th and 18th century Nichols newspapers collection',
    '3548' => '17th-18th century Burney Collection newspapers',
    '3250' => 'ABI/INFORM Complete (ProQuest)',
    '456' => 'Abstracts in Anthropology Online',
    '556' => 'Abstracts in Social Gerontology',
    '1' => 'Academic Search Premier',
    '40' => 'Access UN',
    '334' => 'AGIS Plus Text',
    '10' => 'Agricola (National Agricultural Library Catalog)',
    '565' => 'America: History and Life (EBSCO)',
    '3426' => 'American Antiquarian Society (AAS) Historical Periodicals Collection...',
    '83' => 'American Chemical Society (ACS)',
    '3142' => 'American Economic Association',
    '421' => 'American Film Scripts Online (AFSO)',
    '167' => 'American Mathematical Society',
    '165' => 'American Physical Society',
    '319' => 'American Society for Microbiology (ASM)',
    '113' => 'American Society of Mechanical Engineers (ASME)',
    '3530' => 'Americas Historical Newspapers: Early American Newspapers',
    '327' => 'Année philologique',
    '398' => 'Annual Bibliography of English Language and Literature (ABELL)',
    '307' => 'Annual Reviews',
    '335' => 'Anthropology Plus',
    '1710' => 'AnthroSource',
    '32' => 'Aquatic Sciences and Fisheries Abstracts (ASFA)',
    '23' => 'Art Index',
    '450' => 'ARTstor',
    '1826' => 'arXiv.org',
    '114' => 'ASCE Library eJournals (American Society of Civil Engineers)',
    '422' => 'Asian American Drama',
    '95' => 'Association for Computing Machinery (ACM) Digital Library',
    '3365' => 'ASTM Compass - International Standards &amp; Digital Library',
    '347' => 'ATLA Religion Database',
    '3605' => 'BCC Research Academic Library',
    '344' => 'Bepress Legal Repository',
    '22' => 'Bibliography of Native North Americans',
    '543' => 'Biological Abstracts (now in BIOSIS Citation Index)',
    '348' => 'BioMed Central (Open Access Journals)',
    '1706' => 'BIOSIS Citation Index (Including Biological Abstracts)',
    '423' => 'Black Drama',
    '424' => 'Black Thought and Culture',
    '425' => 'British and Irish Women\'s Letters and Diaries',
    '3333' => 'BrowZine',
    '2' => 'Business Source Ultimate (formerly Premier version)',
    '542' => 'CAB Direct',
    '158' => 'Cambridge Core (eBooks &amp; eJournals)',
    '311' => 'Canadian Bar Association',
    '26' => 'Canadian Business and Current Affairs (CBCA) Business (ProQuest)',
    '3055' => 'Canadian Business and Current Affairs (CBCA) Complete (ProQuest)',
    '320' => 'Canadian Business and Current Affairs (CBCA) Current Events (ProQuest...',
    '164' => 'Canadian Business and Current Affairs (CBCA) Education (ProQuest)',
    '27' => 'Canadian Business and Current Affairs (CBCA) Reference (ProQuest)',
    '451' => 'Canadian Newspapers FULLTEXT (Infomart)',
    '368' => 'Canadian Patent Reporter Plus',
    '184' => 'Canadian Periodicals Index Quarterly (CPI.Q)',
    '29' => 'Canadian Research Index (CRI)',
    '596' => 'CARD Online (CARDonline)',
    '313' => 'Centre for Digital Scholarship eJournals (UNB CDS)',
    '511' => 'Charter of Rights in Litigation: Direction from the Supreme Court...',
    '1471' => 'Chemical Abstracts (SciFinder Web)',
    '174' => 'Children\'s Literature Comprehensive Database (CLCD)',
    '577' => 'China: Trade, Politics and Culture, 1793-1980 (Adam Matthew Digital...',
    '186' => 'CHRR (Canadian Human Rights Reporter) Online',
    '161' => 'CINAHL with Full Text (Cumulative Index to Nursing &amp; Allied Health...',
    '594' => 'Classical Scores Library (Music Online)',
    '3509' => 'Cochrane Clinical Answers (CCAs - Wiley)',
    '459' => 'Cochrane Library',
    '544' => 'Communication &amp; Mass Media Complete (CMMC)',
    '326' => 'Computer Source Index (formerly Computer Science Index)',
    '1760' => 'Criminal Justice Abstracts - EBSCO',
    '125' => 'Current Index to Statistics',
    '3262' => 'D&amp;B Hoovers (formerly Hoover\'s Online)',
    '440' => 'Database of Abstracts of Reviews of Effects',
    '3437' => 'De Gruyter Journals',
    '578' => 'Defining Gender, 1450-1910 (Adam Matthew Digital)',
    '557' => 'Digital National Security Archive (DNSA - ProQuest)',
    '345' => 'Directory of Open Access Journals (DOAJ)',
    '44' => 'Dissertations &amp; Theses (ProQuest PQDT: formerly Digital Dissertations...',
    '373' => 'Duke University Press',
    '426' => 'Early Encounters in North America',
    '173' => 'Early English Books Online (EEBO)',
    '3578' => 'Earth, Atmospheric, &amp; Aquatic Science Database (ProQuest)',
    '8' => 'Econlit',
    '521' => 'eHRAF Archaeology',
    '53' => 'eHRAF World Cultures',
    '506' => 'Eighteenth Century Collections Online (ECCO)',
    '587' => 'Eighteenth Century Journals (Adam Matthew Digital)',
    '3370' => 'eMarketer Pro',
    '3629' => 'EMBASE',
    '166' => 'Emerald Journals',
    '579' => 'Empire Online (Adam Matthew Digital)',
    '3403' => 'Engineering Index Backfile (EI - Engineering Village)',
    '9' => 'ERIC - EBSCO',
    '33' => 'ERIC - ProQuest',
    '315' => 'Érudit',
    '391' => 'ESTC  (English Short Title Catalogue)',
    '1692' => 'EThOS (Electronic Theses Online Service : UK Theses)',
    '1786' => 'European Views of the Americas: 1493 to 1750',
    '3232' => 'Films on Demand',
    '3328' => 'Financial times (FT.com)',
    '3327' => 'First Research - Industry Profiles (Mergent Intellect)',
    '297' => 'Forestscience (formerly Forestscience.info)',
    '3630' => 'Forrester Research',
    '3526' => 'Frontier Life: Borderlands, Settlement &amp; Colonial Encounters (Adam...',
    '3405' => 'Frost &amp; Sullivan',
    '18' => 'GeoRef',
    '3547' => 'Gerritsen Collection of Aletta H. Jacobs - Books &amp; Journals',
    '454' => 'Google Scholar',
    '599' => 'Health and Psychosocial Instruments (HaPI : EBSCO)',
    '405' => 'HealthStar',
    '123' => 'HeinOnline',
    '3166' => 'HeinOnline - Canada Supreme Court Reports',
    '3164' => 'HeinOnline - English Reports, Full Reprint (1220-1867)',
    '567' => 'HeinOnline - Foreign &amp; International Law Resources Database',
    '3165' => 'HeinOnline - Harvard Research in International Law',
    '1680' => 'HeinOnline - Philip C. Jessup Library',
    '3290' => 'HeinOnline - Revised Statutes of Canada',
    '3162' => 'HeinOnline - Session Laws Library',
    '3562' => 'HeinOnline - Slavery in America and the World: History, Culture &amp;...',
    '3163' => 'HeinOnline - World Constitutions Illustrated',
    '131' => 'HighWire Press',
    '380' => 'Highwire Press (Open Access)',
    '566' => 'Historical Abstracts (EBSCO)',
    '549' => 'Human Kinetics Publishers, Inc',
    '1709' => 'IBISWorld - US/Canadian &amp; Global Industry Reports',
    '1721' => 'ICE Virtual Library (Institution of Civil Engineers)',
    '3300' => 'ICLR.3',
    '272' => 'IEEE Xplore Digital Library (Current &amp; Archive)',
    '3391' => 'InCites Essential Science Indicators (ESI)',
    '1674' => 'Index to Canadian Legal Literature (Book Reviews subset)',
    '1673' => 'Index to Canadian Legal Literature (Journals and Texts subset)',
    '1794' => 'Index to Legal Periodicals &amp; Books Full Text',
    '1793' => 'Index to Legal Periodicals Retrospective',
    '316' => 'Infomart (formerly FPinfomart.ca) ',
    '1759' => 'Informa Healthcare Journals',
    '3573' => 'INFORMIT Indigenous Collection ',
    '94' => 'IngentaConnect',
    '365' => 'INIS (International Nuclear Information Systems)',
    '462' => 'Inspec (Engineering Village)',
    '84' => 'Institute of Physics Publishing (IOP)',
    '3386' => 'International Bibliography of the Social Sciences (IBSS - ProQuest...',
    '331' => 'Iter - Gateway to the Middle Ages and Renaissance',
    '88' => 'JSTOR Archival Collection',
    '3047' => 'JSTOR Current Collection',
    '116' => 'JustisOne',
    '3340' => 'Kanopy',
    '367' => 'LabourSource',
    '427' => 'Latino Literature',
    '119' => 'LegalTrac',
    '108' => 'Leisure, Recreation and Tourism (see CAB Direct)',
    '409' => 'Library, Information Science &amp; Technology Abstracts (LISTA)',
    '569' => 'Literature Criticism Online',
    '463' => 'Literature Online',
    '312' => 'LLMC-Digital',
    '1817' => 'London Review of Books',
    '400' => 'Longwoods Publishing',
    '1489' => 'Loyalist Collection (Harriet Irving Library), The',
    '1491' => 'Lyell Collection - Geological Society of London',
    '3550' => 'Maclean\'s Magazine Archive (EBSCOhost)',
    '341' => 'Manas Media\'s World Law reform database',
    '3628' => 'ManchesterHive - Gothic eBooks',
    '3416' => 'Market share reporter',
    '472' => 'Martin\'s Online Criminal Code',
    '580' => 'Mass Observation Online (Adam Matthew Digital)',
    '54' => 'MathSciNet',
    '3060' => 'Medcom Video Training Programs Collection',
    '582' => 'Medieval Travel Writing (Adam Matthew Digital)',
    '163' => 'Medline (1950 to Present)',
    '324' => 'Medline (In-Process and Other Non-Indexed Citations)',
    '323' => 'Medline (OldMedline - 1951 to 1965 )',
    '507' => 'Mental Measurements Yearbook (MMY)',
    '3282' => 'Mergent Archives',
    '3317' => 'Mergent Intellect',
    '3059' => 'Mergent Online',
    '3263' => 'Million Dollar Database (D &amp; B/Mergent)',
    '499' => 'MIT Press Journals',
    '325' => 'Modern Language Association (MLA) International Bibliography &amp; Directory...',
    '31' => 'Modern Language Association (MLA) International Bibliography &amp; Directory...',
    '332' => 'MSDS plus CHEMINFO',
    '487' => 'Nation archive',
    '180' => 'National Council of Teachers of English (NCTE)',
    '89' => 'National Research Council (NRC)',
    '3044' => 'Naver News Library',
    '3425' => 'Naxos Music Library (NML)',
    '3270' => 'NFB Campus (National Film Board of Canada)',
    '3200' => 'Nineteenth Century Collections Online (NCCO eBooks)',
    '428' => 'North American Immigrant Letters, Diaries and Oral Histories',
    '429' => 'North American Indian Thought and Culture',
    '430' => 'North American Theatre Online',
    '431' => 'North American Women\'s Drama',
    '432' => 'North American Women\'s Letters and Diaries',
    '554' => 'OECD iLibrary - Books, Papers and Statistics',
    '375' => 'OnePetro (formerly SPE eLibrary)',
    '435' => 'Oral History Online',
    '339' => 'OSH References Databases',
    '127' => 'Ovid Journals - Lippincott Williams &amp; Wilkins Nursing &amp; Health Professions...',
    '171' => 'Oxford University Press Journals',
    '1496' => 'Parliament Rolls of Medieval England (PROME), The',
    '3277' => 'Passport GMID (Global Market Information Database)',
    '644' => 'Past Masters (Intelex)',
    '586' => 'Periodicals Archive Online (PAO - ProQuest)',
    '25' => 'Philosopher\'s Index (ProQuest)',
    '538' => 'PILOTS Database',
    '3612' => 'PitchBook',
    '593' => 'Portico (e-Journals Archive)',
    '1485' => 'PressReader - Worldwide Newspapers **ON-CAMPUS ONLY** (formerly Library...',
    '404' => 'Project Euclid',
    '87' => 'Project Muse',
    '492' => 'ProQuest Historical Newspapers',
    '410' => 'ProQuest Historical Newspapers: The Globe and Mail',
    '159' => 'ProQuest Nursing &amp; Allied Health Source',
    '3387' => 'ProQuest Political Science',
    '3385' => 'ProQuest Politics Collection',
    '336' => 'PsycARTICLES',
    '3291' => 'PsycBOOKS',
    '548' => 'PsychiatryOnline',
    '11' => 'PsycINFO',
    '3253' => 'PsycTESTS',
    '24' => 'Public Affairs Information Service (PAIS) International and Archive...',
    '115' => 'Publisher',
    '452' => 'PubMed',
    '169' => 'PubMed Central (Open Access)',
    '3383' => 'Quebec Government Documents - BAnQ Open Access Collections',
    '471' => 'Quicklaw',
    '85' => 'Royal Society of Chemistry (RSC)',
    '338' => 'RTECS (Registry of Toxic Effects of Chemical Substances)',
    '352' => 'SAGE Journals Online',
    '77' => 'Science Direct',
    '1468' => 'SciFinder Web (Chemical Abstracts, CAS React, CAS Registry)',
    '126' => 'Scitation Journals - AIP Publishing (formerly American Institute...',
    '397' => 'Scopus',
    '172' => 'Selected Free eJournals',
    '181' => 'SIAM Journals Online',
    '583' => 'Slavery, Abolition and Social Justice, 1490-2007 (Adam Matthew Digital...',
    '441' => 'Smithsonian Global Sound® for Libraries',
    '68' => 'Social Services Abstracts',
    '541' => 'Social Work Abstracts',
    '3161' => 'SocINDEX with Full Text',
    '35' => 'Sociological Abstracts',
    '12' => 'SportDiscus',
    '86' => 'SpringerLink',
    '3440' => 'Statista',
    '475' => 'Taylor and Francis Online - eJournals',
    '597' => 'Theatre in Video',
    '1715' => 'Thesaurus Linguae Graecae (TLG)',
    '322' => 'Theses Canada Portal',
    '473' => 'Times Digital Archives',
    '3610' => 'Times Literary Supplement Historical Archive (TLS)',
    '3620' => 'Trench Journals and Unit Maga        zines of the First World War (ProQuest...',
    '1683' => 'TRIS (Transportation Research Information Services)',
    '433' => 'Twentieth Century North American Drama',
    '371' => 'U.K. Parliamentary Papers (ProQuest)',
    '3382' => 'U.S. Government Documents (Open Access)',
    '3624' => 'UN iLibrary',
    '3523' => 'UNB Libraries - Government Documents Online (Open Access)',
    '3380' => 'UNB Libraries - SCI-FORF Open Access Collection',
    '3351' => 'UNB Libraries - Selected Newspapers (Online)',
    '3452' => 'Uniform Law Conference of Canada (ULCC)',
    '3418' => 'University of Chicago Press Journals',
    '3491' => 'UpToDate',
    '545' => 'Violence &amp; Abuse Abstracts',
    '584' => 'Vividata',
    '455' => 'Wildlife &amp; Ecology Studies Worldwide',
    '132' => 'Wiley Online Library',
    '434' => 'Women and Social Movements in the United States, 1600-2000 (Basic...',
    '340' => 'Women\'s Studies International',
    '403' => 'World Shakespeare Bibliography Online',
    '80' => 'Worldwide Political Science Abstracts (ProQuest)',
  ];

  return $titles;
}

/**
 * Get UNB Libraries department label, given an email mailbox.
 *
 * @param string $mailbox
 *   A email mailbox string identifying a UNB Libraries Department without a Drupal user account.
 *
 * @return string
 *   The name of the UNB Libraries department.
 */
function _lib_core_contactable_department($mailbox) {
  // Contact webform may send messages to the following mailboxes.
  $departments = [
    'archives' => 'Archives',
    'circhi' => 'Access Services',
    'digitalscholar' => 'Centre for Digital Scholarship',
    'docdel' => 'Document Delivery',
    'englib' => 'Engineering & Computer Science',
    'hilref' => 'Reference',
    'library' => 'Staff',
    'libweb' => 'Website Administrator',
    'govdocs' => 'Government Documents, Data and Maps',
    'hwkcommons' => 'Hans W. Klohn Commons',
    'lawlib' => 'Law Library',
    'mic' => 'Microforms',
    'scilib' => 'Science & Forestry',
  ];

  return array_key_exists($mailbox, $departments) ? $departments[$mailbox] : NULL;
}

/**
 * Implements hook_views_query_alter().
 */
function lib_core_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  if ($view->id() != 'content') {
    return;
  }

  $user = Drupal::currentUser();
  if (!$user->hasPermission('edit any library_page content')) {
    $query->addWhere(1, 'type', 'library_page', '!=');
  }
  if (!$user->hasPermission('edit any news_post content')) {
    $query->addWhere(1, 'type', 'news_post', '!=');
  }
}
