language: php

services:
  - docker

php:
  - '7.2'

git:
  depth: 1

before_install:
  - curl -Ls https://raw.githubusercontent.com/unb-libraries/dockworker/3.x/scripts/travis/init.sh | bash
  - composer install

script:
  - set -e
  - vendor/bin/dockworker local:build-test
  - vendor/unb-libraries/dockworker/scripts/kubectl/init.sh
  - vendor/bin/dockworker image:deploy $TRAVIS_BRANCH
  - vendor/bin/dockworker deployment:logs:check $TRAVIS_BRANCH
  - vendor/unb-libraries/dockworker/scripts/kubectl/notifyNewRelicDeployment.sh

notifications:
  slack:
    rooms:
      secure: SpBbfBfKqy4dAI0DA7ufPO0x3hn971SWvkso8fk+DgwEFkULfFTpbBM/peSvhFtgNcSc9DxZ8q9hvRcOcYlgfqt1f0e9LFOm+uKSLAYtjdqngqAZQlSx1cF3DNA77qlD/83N4GOtk+WLN7moiL8Qx6tVacBd+9Tv9V7ODLqx+tFZdwrzhLuBIFIFlF2il5aTjkgv4JzBCf19Cp6cRDoUcv9/EoDYBgnXXZ7K5Cry21gCHKB8pB9dCOOtvTrw5fvgLejaHruWykx8rLQzNpHS9HI3dlyxmpwSaEcWDWlE8ZSIcCZBg4Kt0iyl2C0Kkrux+Y3dWhpvVRcHZ5Bzkv0NQr0d83oQ/PxO+MW8Ysl5CIFcnEwVE/C3yUaHsLmPircBpyo6oFxM1WNGL1eoMr5oN9YRuukgE0Plq6SL+gcG8xbjFww93wSzeNLoLcYFO8MPzj8AFOHlmM8j55vUm+cmel+noT0nwq8+OGPuOo2Zb4YS2MuApty/QNuxsrHUN2QjgqtW3Pz6wPAB2WwlnanqiSWHtRl+ECATIdkBoAkQdQ2sWLT099WlMksDwfSweFO2nvyiSjMevGqbGHg2K6Fooczc8xoboV+gi6jQlb9SVb2YnFtSGkFFdeKZ2Dz98nXrhGyh+8UgHEB8KHgdxV9aCiFdem5Hq0VGc7p4THCWvY8=
    on_start: always
    on_success: always
