version: '3.6'

services:
  mysql:
    image: mysql:5.7
    restart: always
    command: mysqld --skip-name-resolve --max_allowed_packet=64M
    env_file:
      - ./env/mysql.env
    expose:
     - "3306"
    networks:
      - lib.unb.ca

  lib.unb.ca:
    build:
      context: .
      args:
        - COMPOSER_DEPLOY_DEV=dev
    restart: always
    container_name: lib.unb.ca
    depends_on:
      - mysql
    expose:
      - "80"
    networks:
      - lib.unb.ca
    ports:
      - "3100:80"
    env_file:
      - ./env/drupal.env
    volumes:
      - ./config-yml:/app/configuration
      - ./custom/modules:/app/modules/custom
      - ./custom/themes:/app/themes/custom
      - ./tests:/app/tests

networks:
  lib.unb.ca:
    name: lib.unb.ca
