services:
  drupal-mysql-lib-unb-ca:
    image: mariadb:10.11
    restart: unless-stopped
    command: mysqld --skip-name-resolve --max_allowed_packet=64M
    env_file:
      - ./env/mysql.env
    expose:
      - "3306"
    networks:
      - lib.unb.ca
    volumes:
      - mysql-data:/var/lib/mysql
  drupal-solr-lib-unb-ca:
    image: ghcr.io/unb-libraries/solr-drupal:8.x-4.x
    restart: unless-stopped
    env_file:
      - ./env/solr.env
    expose:
      - "8983"
    networks:
      - lib.unb.ca
    entrypoint:
      - docker-entrypoint-multiple.sh
      - pages.lib.unb.ca:/solr-conf
    volumes:
      - solr-data:/opt/solr/server/solr/mycores
  drupal-redis-lib-unb-ca:
    image: redis:5-alpine
    restart: unless-stopped
    expose:
      - "6379"
    networks:
      - lib.unb.ca
    env_file:
      - ./env/redis.env
  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
    expose:
      - "1025"
      - "8025"
    ports:
      - "4101:8025"
    networks:
      - lib.unb.ca
  lib-unb-ca:
    build:
      context: .
    restart: unless-stopped
    container_name: lib-unb-ca
    depends_on:
      - drupal-mysql-lib-unb-ca
      - drupal-solr-lib-unb-ca
      - drupal-redis-lib-unb-ca
    expose:
      - "80"
    networks:
      - lib.unb.ca
    ports:
      - "3101:80"
    env_file:
      - ./env/drupal.env
    volumes:
      - drupal-data:/app/html/sites/default
      - ./configuration:/app/configuration
      - ./custom/modules:/app/html/modules/custom
      - ./custom/themes:/app/html/themes/custom
      - ./tests:/app/tests
networks:
  lib.unb.ca:
    name: lib.unb.ca
volumes:
  drupal-data:
  mysql-data:
  solr-data:
