<?php

/**
 * @file
 * Contains lib_unb_ca_page_text_content.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Render\Markup;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\lib_unb_ca_page_text_content\PageTextHelper;
use Drupal\node\NodeInterface;

/**
 * Implements hook_help().
 */
function lib_unb_ca_page_text_content_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the lib_unb_ca_page_text_content module.
    case 'help.page.lib_unb_ca_page_text_content':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Extract textual content from UNB Libraries pages') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_node_presave().
 */
function lib_unb_ca_page_text_content_node_presave(NodeInterface $node) {
  if ($node->bundle() == 'library_page' || $node->bundle() == 'news_post') {
    $node->set('field_unb_lib_page_content', PageTextHelper::getPageTextualContent($node));
  }
}

/**
 * Implements hook_node_view().
 */

function lib_unb_ca_page_text_content_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) { 
  // Remove extraneous divs from html
  $build['#post_render'][] = function ($html, array $elements) {
    // Match media figures
    $pattern = '#(<figure class="media-figure">)(.|[\r\n])*?(</figure>)#';
    // Recover html string from markup object
    $markup = $html->__toString();
    $search = preg_match_all($pattern, $markup, $mfigs);
    
    // Iterate through figures
    foreach ($mfigs[0] as $mfig) {
      // Match all <div*> tags
      $pattern = '#<figure class="media-figure">((.|[\r\n])*?)<img#';
      $search = preg_match($pattern, $mfig, $remove);
      $remove = $remove[1] ?? '';
      // Remove <div> tags
      $replace = str_replace($remove, '', $mfig);
      // Remove </div> closers
      $replace = str_replace('</div>', '', $replace);
      // Replace original figure with one 
      $markup = str_replace($mfig, $replace, $markup);
    }
    
    // Return markup object from new html
    return Markup::create($markup);
  };
}