apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: drupal
    appMajor: "8"
    instance: lib.unb.ca
    tier: frontend
    uri: lib.unb.ca
    vcsOwner: unb-libraries
    vcsRepository: lib.unb.ca
    vcsRef: prod
  name: lib-unb-ca
  namespace: prod
spec:
  selector:
    matchLabels:
      uri: lib.unb.ca
  replicas: 3
  revisionHistoryLimit: 2
  minReadySeconds: 45
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: drupal
        appMajor: "8"
        instance: lib.unb.ca
        tier: frontend
        uri: lib.unb.ca
        vcsOwner: unb-libraries
        vcsRepository: lib.unb.ca
        vcsRef: prod
    spec:
      nodeSelector:
        deployenv: prod
      containers:
        -
          name: lib-unb-ca
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 100
            timeoutSeconds: 3
            periodSeconds: 15
          env:
            -
              name: DEPLOY_ENV
              value: prod
            -
              name: MYSQL_HOSTNAME
              value: drupal-mysql-lib-unb-ca
            -
              name: MYSQL_PORT
              value: "3306"
            -
              name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: root-password
            -
              name: NR_INSTALL_KEY
              valueFrom:
                secretKeyRef:
                  name: newrelic
                  key: install-key
            -
              name: OCLC_API_IDM_WSKEY
              valueFrom:
                secretKeyRef:
                  name: oclc-idm-wskey
                  key: wskey
            -
              name: OCLC_API_IDM_SECRET
              valueFrom:
                secretKeyRef:
                  name: oclc-idm-wskey
                  key: secret
            -
              name: OCLC_API_LMAN_WSKEY
              valueFrom:
                secretKeyRef:
                  name: oclc-lman-wskey
                  key: wskey
            -
              name: OCLC_API_LMAN_SECRET
              valueFrom:
                secretKeyRef:
                  name: oclc-lman-wskey
                  key: secret
            -
              name: OCLC_API_WSKEY
              valueFrom:
                secretKeyRef:
                  name: oclc-wskey
                  key: wskey
            -
              name: OCLC_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: oclc-wskey
                  key: secret
            -
              name: OCLC_API_KB
              valueFrom:
                secretKeyRef:
                  name: oclc-kb
                  key: wskey
          image: "||DEPLOYMENTIMAGE||"
          imagePullPolicy: Always
          ports:
            -
              containerPort: 80
          volumeMounts:
            -
              mountPath: /app/html/sites/default
              name: drupal-persistent-storage
      priorityClassName: high-priority-services
      imagePullSecrets:
        -
          name: github-container-registry-auth
      restartPolicy: Always
      volumes:
        -
          name: drupal-persistent-storage
          persistentVolumeClaim:
            claimName: lib-unb-ca
