<?php

/**
 * @file
 * Contains guides.module.
 */

use Drupal\Core\Render\Element;
use Drupal\Core\Form\FormStateInterface;
use Drupal\user\Entity\User;

/**
 * Implements hook_preprocess_field_multiple_value_form().
 *
 * Set custom "add more X" button values.
 */
function guides_preprocess_field_multiple_value_form(&$variables) {
  $values = [
    'related_guide_categories_add_more' => 'Add Another Category',
    'contacts_add_more' => 'Add Another Contact',
  ];

  if (isset($variables['element']['add_more']['#name'])) {
    $name = $variables['element']['add_more']['#name'];
    if (isset($values[$name])) {
      $variables['button']['#value'] = t($values[$name]);
    }
  }
}

function guides_form_guide_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $entity = $form_state->getFormObject()->getEntity();
  if ($entity->isNew()) {
    $user = User::load(\Drupal::currentUser()->id());
    $form['editors']['widget'][0]['subform']['field_user']['widget'][0]['target_id']['#default_value'] = $user;
  }
}
