<?php

/**
 * @file
 * Contains portolan.module.
 */

/**
 * Implements hook_theme().
 */
function portolan_theme($existing, $type, $theme, $path) {
  return [
    'portolan_record' => [
      'render element' => 'elements',
    ],
    'portolan_record__search_excerpt' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for portolan_record templates.
 *
 * Default template: portolan-record.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the user information and any
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_portolan_record(array &$variables) {
  $variables['portolan_record'] = $variables['elements']['#portolan_record'];
}

/**
 * Prepares variables for portolan_record__search_excerpt templates.
 *
 * Default template: portolan-record--search-excerpt.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the user information and any
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_portolan_record__search_excerpt(array &$variables) {
  $variables['portolan_record'] = $variables['elements']['#portolan_record'];
  $variables['search_api_excerpt'] = $variables['elements']['#search_api_excerpt'];
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function portolan_theme_suggestions_portolan_record(array $variables) {
  $suggestions = [];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');
  $suggestions[] = 'portolan_record__' . $sanitized_view_mode;
  return $suggestions;
}