<?php

/**
 * @file
 * Contains ior.module.
 */

/**
 * Implements hook_theme().
 */
function ior_theme($existing, $type, $theme, $path) {
  return [
    'contest' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for contest templates.
 *
 * Default template: contest.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the user information and any
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_contest(array &$variables) {
  $variables['contest'] = $variables['elements']['#contest'];
}
