<?php

/**
 * @file
 * Contains ior_awards.module.
 */

/**
 * Implements hook_theme().
 */
function ior_awards_theme($existing, $type, $theme, $path) {
  return [
    'contest' => [
      'base hook' => 'contest',
      'preprocess functions' => array_merge($existing['contest']['preprocess functions'], [
        'ior_awards_template_preprocess_contest',
      ]),
    ],
    'ior_submission' => [
      'base hook' => 'ior_submission',
    ],
    'ior_submission__winner' => [
      'render element' => 'ior_submission',
    ],
    'ior_award' => [
      'render element' => 'award',
    ],
    'ior_award__badge' => [
      'base hook' => 'ior_award',
    ],
    'ior_award__winner' => [
      'base hook' => 'ior_award',
    ],
    'page_title__ior_submission' => [
      'base hook' => 'page_title',
    ],
  ];
}

/**
 * Prepares variables for contest templates.
 *
 * Default template: contest.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the user information and any
 *   - attributes: HTML attributes for the containing element.
 */
function ior_awards_template_preprocess_contest(array &$variables) {
  /** @var \Drupal\ior\Entity\ContestInterface $contest */
  $contest = $variables['elements']['#contest'];
  foreach (Drupal::entityTypeManager()->getStorage('ior_collection')->loadByContest($contest->id()) as $collection) {
    $variables['contest']['collections'][$collection->id()] = [
      'url' => \Drupal\Core\Url::fromRoute('view.ior_contest_collection.page_1', [
        'contest' => $contest->id(),
        'collection' => $collection->id(),
      ]),
      'title' => $collection->get('field_title')->value,
    ];
  }

  $variables['contest']['winners_url'] = \Drupal\Core\Url::fromRoute('view.ior_contest_winners.page_1', [
    'contest' => $contest->id(),
  ])->toString();
}

/**
 * Prepares variables for submission templates.
 *
 * Default template: ior-submission.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the user information and any
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_ior_submission__winner(array &$variables) {
  /** @var \Drupal\ior\Entity\SubmissionInterface $submission */
  $submission = $variables['elements']['#ior_submission'];
  $variables['submission']['entity'] = $submission;
  foreach (\Drupal\Core\Render\Element::children($variables['elements']) as $key) {
    if ($submission->hasField($key) && !empty($submission->get($key)->getValue())) {
      $variables['submission'][$key] = $variables['elements'][$key];
      $variables['submission'][$key]['#label_display'] = 'hidden';
    }
  }
  $variables['submission']['url'] = $submission->toUrl()->toString();

  // This should be done in a template?
  $variables['submission']['field_first_name']['#attributes']['class'][] = 'd-inline';
  $variables['submission']['field_last_name']['#attributes']['class'][] = 'd-inline';
  $variables['submission']['field_department']['#attributes']['class'][] = 'd-inline';
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function ior_awards_theme_suggestions_ior_award_alter(array &$suggestions, array $variables) {
  $view_mode_suggestion = strtr($variables['award']['#view_mode'], '.', '_');
  if (!in_array($view_mode_suggestion, $suggestions)) {
    $suggestions[] = 'ior_award__' . $view_mode_suggestion;
  }
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function ior_awards_theme_suggestions_page_title(array $variables) {
  $suggestions = [];
  if (_get_submission_from_route()) {
    $suggestions[] = 'page_title__ior_submission';
  }
  return $suggestions;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ior_awards_preprocess_page_title(array &$variables) {
  if ($submission = _get_submission_from_route()) {
    $view_builder = Drupal::entityTypeManager()->getViewBuilder('ior_award');
    $variables['awards'] = array_map(function (\Drupal\ior_awards\Entity\AwardInterface $award) use ($view_builder) {
      return $view_builder->view($award, 'badge');
    }, $submission->get('field_awards')->referencedEntities());
  }
}

/**
 * Load a submission entity from the current route.
 *
 * @return \Drupal\ior\Entity\SubmissionInterface|false
 *   A submission entity. False if the current route does not contain a
 *   parameter that resolves to a submission entity.
 */
function _get_submission_from_route() {
  $route_match = Drupal::routeMatch();
  if ($route_match->getRouteName() !== 'entity.ior_submission.canonical') {
    return FALSE;
  }

  /** @var \Drupal\ior\Entity\SubmissionInterface $submission */
  if ($submission = $route_match->getParameter('ior_submission')) {
    return $submission;
  }
  return FALSE;
}

/**
 * Implements hook_entity_type_alter().
 */
function ior_awards_entity_type_alter(array &$entity_types) {
  /** @var \Drupal\Core\Entity\ContentEntityTypeInterface $submission */
  $submission = $entity_types['ior_submission'];
  $submission->setFormClass('review', $submission->getFormClass('default'));

  $canonical_path = $submission->getLinkTemplate('canonical');
  $submission->setLinkTemplate('review-form', "{$canonical_path}/review");
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 *
 * Create aliases for "ior_contest_winners", "ior_awards", "ior_collections" views.
 */
function ior_awards_contest_insert(ContestInterface $contest) {
  $view_storage = Drupal::entityTypeManager()
    ->getStorage('view');
  foreach ($view_storage->loadMultiple(['ior_contest_winners', 'ior_awards', 'ior_collections']) as $view) {
    Drupal::service('views.alias_generator')
      ->generateViewAlias($view, $contest);
  }
}
