<?php

/**
 * @file
 * Contains lib_unb_ca_user_protect.module.
 */

use Drupal\Core\Cache\RefinableCacheableDependencyInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Render\Markup;

/**
 * Implements hook_help().
 */
function lib_unb_ca_user_protect_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the lib_unb_ca_user_protect module.
    case 'help.page.lib_unb_ca_user_protect':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Prevent users from editing upstream field data') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_FORMID_alter().
 */
function lib_unb_ca_user_protect_form_user_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $warning = Markup::Create('Directory Info metadata is maintained centrally, displayed on our Staff Directory and should generally mirror UNB\'s Colleague-driven data. <a href="/contact-unb-libraries-staff?recipient=pollockl">Contact Lisa Pollock</a> if you encounter errors.');
  \Drupal::messenger()->addWarning($warning);

  $user = \Drupal::currentUser();
  if (!$user->hasPermission('edit any user details')) {
    foreach (Element::children($form) as $key) {
      $form[$key]['#disabled'] = TRUE;
    }
  }
  elseif (\Drupal::currentUser()->id() != 1) {
    // Exclude super user from exclusions.
    foreach (Element::children($form) as $key) {
      switch ($key) {
        case 'account':
          if ($form_state->getFormObject()->getOperation() != 'register') {
            // Disable username + password fields on Edit (but not Add) form.
            $form[$key]['name']['#disabled'] = TRUE;
            $form[$key]['pass']['#disabled'] = TRUE;
          }
          // Disable selected account fields.
          if (!$user->hasPermission('edit any user details')) {
            $form[$key]['mail']['#disabled'] = TRUE;
          }
          $form[$key]['notify']['#disabled'] = TRUE;
          break;

        case 'actions':
          // Disable Cancel account link.
          $form[$key]['delete']['#disabled'] = TRUE;
          break;

        case 'simple_groups':
          // Disable Groups fields.
          $form[$key]['#disabled'] = TRUE;
          break;
      }
    }
  }
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function lib_unb_ca_user_protect_menu_local_tasks_alter(&$data, $route_name, RefinableCacheableDependencyInterface &$cacheability) {
  $applicable_routes = ['entity.user.canonical'];
  if (in_array($route_name, $applicable_routes)) {
    $user = \Drupal::currentUser();
    if (!$user->hasPermission('edit any user details')) {
      unset($data['tabs'][0]['entity.user.edit_form']);
    }
  }
}
