apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-lib-unb-ca
  namespace: dev
  labels:
    app: drupal
    tier: cron
spec:
  schedule: "10,25,40,55 * * * *"
  startingDeadlineSeconds: 480
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      name: cron-lib-unb-ca
      labels:
        app: drupal
        tier: cron
    spec:
      template:
        spec:
          nodeSelector:
            deployenv: dev
          containers:
            -
              name: cron-lib-unb-ca
              command:
                - /scripts/drupalCronEntry.sh
              env:
                -
                  name: DEPLOY_ENV
                  value: dev
                -
                  name: MYSQL_HOSTNAME
                  value: drupal-mysql-lib-unb-ca
                -
                  name: MYSQL_PORT
                  value: "3306"
                -
                  name: OCLC_API_IDM_WSKEY
                  valueFrom:
                    secretKeyRef:
                      name: oclc-idm-wskey
                      key: wskey
                -
                  name: OCLC_API_IDM_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: oclc-idm-wskey
                      key: secret
                -
                  name: OCLC_API_LMAN_WSKEY
                  valueFrom:
                    secretKeyRef:
                      name: oclc-lman-wskey
                      key: wskey
                -
                  name: OCLC_API_LMAN_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: oclc-lman-wskey
                      key: secret
                -
                  name: OCLC_API_WSKEY
                  valueFrom:
                    secretKeyRef:
                      name: oclc-wskey
                      key: wskey
                -
                  name: OCLC_API_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: oclc-wskey
                      key: secret
                -
                  name: OCLC_API_KB
                  valueFrom:
                    secretKeyRef:
                      name: oclc-kb
                      key: wskey
              image: "||DEPLOYMENTIMAGE||"
              imagePullPolicy: Always
              volumeMounts:
                -
                  mountPath: /app/html/sites/default
                  name: drupal-persistent-storage
                -
                  name: oclc-sftp-key
                  mountPath: "/app/keys/oclc-sftp.root.key"
                  subPath: "oclc-sftp.root.key"
          priorityClassName: cron-priority-services
          imagePullSecrets:
            -
              name: github-container-registry-auth
          restartPolicy: Never
          volumes:
            -
              name: drupal-persistent-storage
              persistentVolumeClaim:
                claimName: lib-unb-ca
            -
              name: oclc-sftp-key
              secret:
                secretName: oclc-sftp-key
                defaultMode: 0400
                items:
                  - key: oclc-sftp.root.key
                    path: oclc-sftp.root.key
