apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: drupal
    appMajor: "9"
    instance: lib.unb.ca
    tier: frontend
    uri: dev-lib.unb.ca
    vcsOwner: unb-libraries
    vcsRepository: lib.unb.ca
    vcsRef: dev
  name: lib-unb-ca
  namespace: dev
spec:
  selector:
    matchLabels:
      uri: dev-lib.unb.ca
  replicas: 1
  revisionHistoryLimit: 2
  minReadySeconds: 45
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: drupal
        appMajor: "9"
        instance: lib.unb.ca
        tier: frontend
        uri: dev-lib.unb.ca
        vcsOwner: unb-libraries
        vcsRepository: lib.unb.ca
        vcsRef: dev
    spec:
      nodeSelector:
        deployenv: dev
      containers:
        -
          name: lib-unb-ca
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 100
            timeoutSeconds: 3
            periodSeconds: 15
          env:
            -
              name: DEPLOY_ENV
              value: dev
            -
              name: MYSQL_HOSTNAME
              value: drupal-mysql-lib-unb-ca
            -
              name: MYSQL_PORT
              value: "3306"
            -
              name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: root-password
            -
              name: NR_INSTALL_KEY
              valueFrom:
                secretKeyRef:
                  name: newrelic
                  key: install-key
            -
              name: OCLC_API_IDM_WSKEY
              valueFrom:
                secretKeyRef:
                  name: oclc-idm-wskey
                  key: wskey
            -
              name: OCLC_API_IDM_SECRET
              valueFrom:
                secretKeyRef:
                  name: oclc-idm-wskey
                  key: secret
            -
              name: OCLC_API_LMAN_WSKEY
              valueFrom:
                secretKeyRef:
                  name: oclc-lman-wskey
                  key: wskey
            -
              name: OCLC_API_LMAN_SECRET
              valueFrom:
                secretKeyRef:
                  name: oclc-lman-wskey
                  key: secret
            -
              name: OCLC_API_WSKEY
              valueFrom:
                secretKeyRef:
                  name: oclc-wskey
                  key: wskey
            -
              name: OCLC_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: oclc-wskey
                  key: secret
            -
              name: OCLC_API_KB
              valueFrom:
                secretKeyRef:
                  name: oclc-kb
                  key: wskey
          image: "||DEPLOYMENTIMAGE||"
          imagePullPolicy: Always
          ports:
            -
              containerPort: 80
          volumeMounts:
            -
              mountPath: /app/html/sites/default
              name: drupal-persistent-storage
            -
              mountPath: /app/private_filesystem
              name: drupal-private-storage
            -
              name: oclc-sftp-key
              mountPath: "/app/keys/oclc-sftp.root.key"
              subPath: "oclc-sftp.root.key"
      priorityClassName: dev-med-priority-services
      imagePullSecrets:
        -
          name: github-container-registry-auth
      restartPolicy: Always
      volumes:
        -
          name: drupal-persistent-storage
          persistentVolumeClaim:
            claimName: lib-unb-ca
        -
          name: drupal-private-storage
          persistentVolumeClaim:
            claimName: lib-unb-ca-private
        -
          name: oclc-sftp-key
          secret:
            secretName: oclc-sftp-key
            defaultMode: 0400
            items:
              - key: oclc-sftp.root.key
                path: oclc-sftp.root.key
