_core:
  default_config_hash: mmRzotiiDIFi2Ozs3xKRCRENuR9Dpd6sXlXoaI8FNTo
applies_admin_routes: false
include_invalid_paths: false
excluded_paths: ''
replaced_titles: ''
custom_paths: "/archives/application-manuscripts :: Archives & Special Collections|/archives :: Application for Use of Manuscripts\r\n/collections/purchase-suggestion :: Collections Development|/collections :: Purchase Suggestion\r\n/collections/stu-monograph-request :: Collections Development|/collections :: STU: UNB Libraries Monograph Request\r\n/contact-unb-libraries-staff :: Contact UNB Libraries Staff\r\n/faculty/liaison-librarians/institution ::  Faculty Support|/faculty :: Contact a Liaison Librarian|/faculty/contact-liaison-librarian :: UNB Fredericton\r\n/faculty/liaison-librarians/institution/unbsj ::  Faculty Support|/faculty :: Contact a Liaison Librarian|/faculty/contact-liaison-librarian :: UNB Saint John\r\n/faculty/liaison-librarians/institution/stu ::  Faculty Support|/faculty :: Contact a Liaison Librarian|/faculty/contact-liaison-librarian :: St. Thomas University\r\n/faculty/publishing-support :: Faculty Support|/faculty :: OA Publishing Support\r\n/services/docdel :: Services At UNB Libraries|/services :: Document Delivery\r\n/services/docdel/policies-and-fees :: Services At UNB Libraries|/services :: Document Delivery|/services/docdel :: Document Delivery Policies And Fees\r\n/services/docdel/community-and-alumni-borrowers :: Services At UNB Libraries|/services :: Document Delivery|/services/docdel :: Document Delivery For Community And Alumni Borrowers\r\n/services/film-purchase-request :: Services At UNB Libraries|/services :: Film Purchase Request\r\n/services/material-retrieval :: :: Services At UNB Libraries|/services :: Material Retrieval\r\n/services/recalls :: Services At UNB Libraries|/services :: Recalls\r\n/services/your-comments-and-suggestions :: Services At UNB Libraries|/services :: Your Comments and Suggestions\r\n/researchcommons/space-request :: Harriet Irving Library Research Commons|/researchcommons :: Space Requests\r\n/research/knowledge-synthesis/service-request :: Research Help|/research :: Knowledge Synthesis & Systematic Reviews|/research/knowledge-synthesis :: Application\r\n/eresources/frost :: eResources and Collections | /eresources :: Frost & Sullivan\r\n/eresources/csa :: eResources and Collections | /eresources :: CSA Standards and Codes\r\n/records/schedules/admin :: Retention Schedules|/records/schedules :: Admin"
include_home_segment: true
alternative_title_field: ''
home_segment_title: Home
home_segment_keep: false
include_title_segment: true
title_from_page_when_available: true
title_segment_as_link: false
segments_separator: null
use_menu_title_as_fallback: false
use_page_title_as_menu_title_fallback: false
menu_title_preferred_menu: ''
remove_repeated_segments: true
language_path_prefix_as_segment: false
absolute_paths: false
hide_single_home_item: true
term_hierarchy: true
use_site_title: false
add_structured_data_json_ld: false
capitalizator_mode: none
capitalizator_ignored_words: {  }
capitalizator_forced_words: {  }
capitalizator_forced_words_case_sensitivity: false
capitalizator_forced_words_first_letter: false
follow_redirects: false
limit_segment_display: false
segment_display_limit: null
segment_display_minimum: 1
truncator_mode: false
truncator_length: null
truncator_dots: false
remove_repeated_segments_text_only: false
home_segment_validation_skip: false
