applies_admin_routes: false
include_home_segment: true
home_segment_title: Home
home_segment_keep: false
include_title_segment: true
language_path_prefix_as_segment: false
use_menu_title_as_fallback: false
use_page_title_as_menu_title_fallback: false
remove_repeated_segments: true
term_hierarchy: true
absolute_paths: false
hide_single_home_item: true
title_from_page_when_available: true
_core:
  default_config_hash: mmRzotiiDIFi2Ozs3xKRCRENuR9Dpd6sXlXoaI8FNTo
include_invalid_paths: false
excluded_paths: ''
replaced_titles: ''
custom_paths: "/faculty/liaison-librarians/institution ::  Faculty Support|/faculty :: Liaison Librarians|/faculty/liaison-librarians-and-departmental-representatives/institution :: UNB Fredericton\r\n/faculty/liaison-librarians/institution/unbsj ::  Faculty Support|/faculty :: Liaison Librarians|/faculty/liaison-librarians-and-departmental-representatives/institution :: UNB Saint John\r\n/faculty/liaison-librarians/institution/stu ::  Faculty Support|/faculty :: Liaison Librarians|/faculty/liaison-librarians-and-departmental-representatives/institution :: St. Thomas University\r\n"
segments_separator: null
title_segment_as_link: false
