drupalAcctProvisionServer: unb_libraries_ldap
ldapEntryProvisionServer: null
drupalAcctProvisionTriggers:
  drupal_on_login: drupal_on_login
  drupal_on_update_create: drupal_on_update_create
ldapEntryProvisionTriggers:
  ldap_on_update_create: '0'
  ldap_on_login: '0'
  ldap_on_delete: '0'
  drupal_on_manual_creation: '0'
userUpdateCronQuery: none
userUpdateCronInterval: monthly
orphanedDrupalAcctBehavior: ldap_user_orphan_do_not_check
orphanedCheckQty: null
orphanedAccountCheckInterval: always
userConflictResolve: resolve
manualAccountConflict: conflict_show_option
acctCreation: user_settings_for_ldap
disableAdminPasswordField: true
ldapUserSyncMappings:
  drupal:
    field-field_first_name:
      ldap_attr: '[givenname]'
      user_attr: '[field.field_first_name]'
      convert: false
      direction: drupal
      user_tokens: ''
      config_module: ldap_user
      prov_module: ldap_user
      enabled: true
      prov_events:
        - create_drupal_user
    field-field_last_name:
      ldap_attr: '[sn]'
      user_attr: '[field.field_last_name]'
      convert: false
      direction: drupal
      user_tokens: ''
      config_module: ldap_user
      prov_module: ldap_user
      enabled: true
      prov_events:
        - create_drupal_user
    field-field_phone_number:
      ldap_attr: '[telephonenumber]'
      user_attr: '[field.field_phone_number]'
      convert: false
      direction: drupal
      user_tokens: ''
      config_module: ldap_user
      prov_module: ldap_user
      enabled: true
      prov_events:
        - create_drupal_user
    field-field_room_number:
      ldap_attr: '[l]'
      user_attr: '[field.field_room_number]'
      convert: false
      direction: drupal
      user_tokens: ''
      config_module: ldap_user
      prov_module: ldap_user
      enabled: true
      prov_events:
        - create_drupal_user
    field-field_position_title:
      ldap_attr: '[title]'
      user_attr: '[field.field_position_title]'
      convert: false
      direction: drupal
      user_tokens: ''
      config_module: ldap_user
      prov_module: ldap_user
      enabled: true
      prov_events:
        - create_drupal_user
  ldap: {  }
