_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
theme: current
defaults:
  sender: php_mail
  formatter: php_mail
modules:
  ior: {  }
  custom_entity_mail:
    none:
      formatter: mime_mail
  webform:
    none:
      sender: mime_mail
      formatter: mime_mail
